import type { Metadata } from "next";
import { notFound } from "next/navigation";

const wiki = {
  "what-is-airport-vpn": { category: "基础概念", title: "机场 VPN 是什么？机场、节点和订阅有什么区别？", intro: "机场通常指提供代理节点订阅服务的平台，用户通过客户端导入订阅后，可以选择不同地区的线路进行连接。", sections: [{ h: "机场是什么？", p: "机场是对代理节点订阅服务的俗称。它通常提供多个地区的节点、流量套餐、订阅地址和使用说明，用户再通过 Clash、Shadowrocket、sing-box 等客户端连接。" }, { h: "节点和线路有什么区别？", p: "节点是客户端里可以选择的具体入口，线路则描述数据经过的网络路径。同一机场可能同时提供普通中转、专线和不同地区的节点。" }, { h: "订阅链接是什么？", p: "订阅链接通常包含节点配置，客户端可以通过它获取或更新节点列表。订阅链接属于敏感信息，不应公开分享，也不应放入公开测速数据。" }] },
  "iepl-iplc-dedicated-line": { category: "线路类型", title: "IEPL 和 IPLC 专线是什么？和普通中转有什么区别？", intro: "IEPL 和 IPLC 常被用于描述跨境专线类型，通常强调更稳定的网络路径和更好的高峰期表现。", sections: [{ h: "专线通常解决什么问题？", p: "专线的核心价值通常是减少公共网络路径上的拥堵和波动，但实际效果取决于入口、出口、地区、运营商和服务商容量。" }, { h: "专线一定更快吗？", p: "不一定。专线可能带来更低的抖动和更稳定的高峰体验，但最终仍需看同一时间、同一地区下的实测数据，不能只根据线路名称判断。" }, { h: "普通中转适合谁？", p: "普通中转价格通常更低，适合网页浏览、轻量视频和备用线路。对稳定性要求较高的用户，可以把专线和中转组合比较。" }] },
  "latency-and-jitter": { category: "测速指标", title: "延迟和抖动怎么看？多少 ms 才算流畅？", intro: "延迟反映数据往返所需时间，抖动反映延迟变化幅度。两个指标都不能脱离使用场景单独判断。", sections: [{ h: "延迟是什么？", p: "延迟通常以 ms 表示，数值越低，交互响应越快。网页浏览对延迟有一定容忍度，实时语音、视频会议和游戏会更依赖低延迟。" }, { h: "抖动为什么重要？", p: "抖动较大时，连接响应会忽快忽慢，可能导致语音断续、画面卡顿或实时操作不稳定。观察平均值之外，也应关注高峰时段的波动。" }, { h: "如何比较？", p: "建议在相同地区、运营商、节点和时间段测试，记录平均延迟、最大延迟、抖动和失败次数，而不是只截取一次 ping 结果。" }] },
  "vpn-test-methodology": { category: "测试方法", title: "机场 VPN 怎么测才不容易被单次速度误导？", intro: "一次测速只能说明某个时间点的状态，不能直接代表一条线路的长期体验。", sections: [{ h: "先固定测试条件", p: "测试时应记录地区、运营商、设备、协议、节点和时间段。只有条件尽量一致，多个服务之间的横向比较才有意义。" }, { h: "至少覆盖白天与晚高峰", p: "白天速度好不等于晚高峰稳定。应把晚高峰作为独立样本，观察延迟上升、下载下降和连接失败是否集中出现。" }, { h: "用趋势替代单次结论", p: "建议观察 7 天以上的成功率、平均延迟、抖动和速度变化。短期峰值可以作为参考，但不应直接成为推荐理由。" }, { h: "按自己的运营商验证", p: "同一个节点在移动、联通和电信下可能出现不同表现。公开榜单适合初步筛选，最终选择应参考与你相同运营商、相近地区和相近时段的记录。" }] },
  "peak-hour-testing": { category: "测试方法", title: "为什么要看晚高峰测速？白天速度快有用吗？", intro: "晚高峰通常是网络负载较高的时段，更容易暴露线路的拥堵、降速和断线问题。一次测速只能说明某个时间点，不能直接代表长期体验。", sections: [{ h: "先固定测试条件", p: "测试时应记录地区、运营商、设备、协议、节点和时间段。只有条件尽量一致，多个服务之间的横向比较才有意义。" }, { h: "什么时间算晚高峰？", p: "不同地区时间可能不同，常见观察窗口是本地时间 20:00 到 24:00。测试报告应标注具体日期和时间，而不是笼统写成高峰期。" }, { h: "重点看哪些变化？", p: "比较白天与晚高峰的延迟、下载速度、抖动、连接成功率和重连时间。速度下降比例和失败记录往往比单次最高速度更有参考价值。" }, { h: "为什么要连续测试？", p: "一天的异常可能来自本地网络、服务维护或临时拥堵。连续 7 天采样可以减少偶然性，更接近日常使用中的真实表现。" }] },
  "streaming-unlock-testing": { category: "使用场景", title: "机场的流媒体解锁测试应该怎么看？", intro: "流媒体解锁测试回答的是某个节点能否访问特定服务，不等于这个节点在所有时段都稳定或速度足够。", sections: [{ h: "解锁测试记录什么？", p: "应记录测试日期、节点地区、服务名称、账号地区和测试结果。Netflix、Disney+、YouTube Premium 以及 AI 服务的判断条件可能不同。" }, { h: "解锁成功就够了吗？", p: "不够。还需要结合晚高峰速度、缓冲情况、画质、延迟和连续播放稳定性。一个能打开页面但经常缓冲的节点，不能算完整的优质体验。" }, { h: "为什么结果会变化？", p: "平台策略、节点 IP、出口地址和服务商线路都可能变化，所以解锁结果应标注测试日期，不能永久承诺。" }] },
  "monthly-vs-yearly-plan": { category: "套餐选择", title: "机场套餐选月付还是年付？如何降低跑路风险？", intro: "套餐周期越长，单价可能越低，但预付风险也越高。选择时应在价格和可控风险之间取平衡。", sections: [{ h: "月付有什么优点？", p: "月付成本较低，适合新机场试用和需要观察稳定性的用户。先用短周期验证节点、流量规则、客服和退款政策，再决定是否续费。" }, { h: "年付一定划算吗？", p: "年付只有在服务长期稳定、退款规则清晰且用户确定长期使用时才可能划算。低价不应成为一次性大额充值的唯一理由。" }, { h: "购买前检查什么？", p: "建议检查运营时间、套餐流量、设备数量、超量规则、退款条件、客服渠道和服务条款，并保留付款凭证。" }] },
} as const;

export function generateStaticParams() { return Object.keys(wiki).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = wiki[slug as keyof typeof wiki]; if (!item) return {}; return { title: item.title, description: `${item.intro}${item.sections.map((section) => section.p).join("")}`, alternates: { canonical: `/wiki/${slug}` } }; }

export default async function WikiDetailPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = wiki[slug as keyof typeof wiki]; if (!item) notFound(); return <main className="article-detail-shell"><nav className="topbar article-topbar"><a className="brand" href="/"><span className="brand-mark">/</span> 简单节点</a><a className="back-link" href="/wiki">返回机场百科 <span>↗</span></a></nav><article className="article-detail wiki-detail"><p className="eyebrow">{item.category} / 简单节点百科</p><h1>{item.title}</h1><p className="article-intro">{item.intro}</p>{item.sections.map((section) => <section key={section.h}><h2>{section.h}</h2><p>{section.p}</p></section>)}<div className="article-source"><strong>内容声明</strong><p>本文用于解释机场 VPN 相关概念，不构成对任何服务商的稳定性承诺。具体体验请结合公开测试条件和实际使用环境判断。</p></div></article><footer><span className="brand"><span className="brand-mark">/</span> 简单节点</span><span>数据来自公开资料与独立测试，仅供比较参考。</span><span>© 2026 简单节点</span></footer></main>; }
